name: reading_widgets
description: 睿丁英语插件库
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # uikit 基础类及ui控件框架
  jvtd_uikit:
    git:
      url: 'https://github.com/JvtdFlutter/uikit.git'
      ref: 0.1.0+1

  # router 路由导航
  jvtd_router:
    git:
      url: 'https://github.com/JvtdFlutter/router.git'
      ref: 0.0.2

  # list 列表基类
  jvtd_list:
    git:
      url: 'https://github.com/JvtdFlutter/list.git'
      ref: 0.0.2

  # utils 工具类
  jvtd_utils:
    git:
      url: 'https://github.com/JvtdFlutter/utils.git'
      ref: 0.0.4

  # string 语言国际化
  jvtd_string:
    git:
      url: 'https://github.com/JvtdFlutter/string.git'
      ref: 0.0.1

  # dialog 弹窗类
  jvtd_dialog:
    git:
      url: 'https://github.com/JvtdFlutter/dialog.git'
      ref: 0.0.3+1

  # http 接口基础类
  jvtd_http:
    git:
      url: 'https://github.com/JvtdFlutter/http.git'
      ref: 0.0.3

  # sqflite 数据库
  jvtd_sqflite:
    git:
      url: 'https://github.com/JvtdFlutter/sqflite.git'
      ref: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/assets/
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AlibabaPuHuiTiBold
      fonts:
        - asset: lib/fonts/Alibaba-PuHuiTi.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
